account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
]

card/urls.py
from django.urls import path
from . import views

app_name = 'card'

urlpatterns = [
    path('', views.get_all, name='cards'),
    path('<uuid:id>/', views.get, name='card'),
    path('add/', views.add, name='add'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('card.urls')),
    path('', include('base.urls')),
    path('', include('account.urls')),
]

account/models.py
from typing import Any
from django.db import models

import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

class CustomUserManager(UserManager):
    def _create_user(self, name, email, password, **extra_fields):
        if not email:
            raise ValueError('You didn\'t provide a valid email')
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)

        return user
    
    def create_user(self, name=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(name, email, password, **extra_fields)
    
    def create_superuser(self, name: str, email: str | None, password: str | None, **extra_fields: Any) -> Any:
        return self._create_user(name, email, password, **extra_fields)
    
class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

base/models.py
from django.db import models

card/models.py
from django.db import models
import uuid

from account.models import User

class Card(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.TextField(blank=True, null=True)
    link = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, related_name='cards', on_delete=models.CASCADE)

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login

from .models import User

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')

        if email and password:
            user = authenticate(request, email=email, password=password)

            if user is not None:
                auth_login(request, user)

                return redirect('/')
            

    return render(request, 'account/login.html')

def signup(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get('password2', '')

        if name and email and password1 and password2:
            user = User.objects.create_user(name, email, password1)

            return redirect('/login/')
        
    return render(request, 'account/signup.html')

base/views.py
from django.shortcuts import render

card/views.py
from django.shortcuts import render, redirect
from account.models import User
from .models import Card
from django.contrib.auth.decorators import login_required

def get_all(request):
    cards = Card.objects.filter(user=request.user)

    return render(request, 'card/get_all.html', {
        "cards":cards
    })

@login_required
def get(request, pk):
    card = Card.objects.filter(user=request.user).get(pk=pk)

    return render(request, 'card/get.html', {
        'card':card
    })

@login_required
def add(request):
    if request.method == 'POST':
        description = request.POST.get('description', '')
        link = request.POST.get('link', '')

        if link:
            Card.objects.create(description=description, link=link, user=request.user)

            return redirect('/')
        
    return render(request, 'card/add.html')

    

base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
        <h1 class="text-xl text-white"><a href="{% url 'card:cards' %}">Millau</a></h1>

        <div class="space-x-4">
            {% if not request.user.is_authenticated %}
                <a href="{% url 'account:login' %}" class="py-4 px-8 bg-slate-600 text-white">Log in</a>
                <a href="{% url 'account:signup' %}" class="py-4 px-8 bg-sky-600 text-white">Sign up</a>
            {% endif %}
        </div>
    </nav>

    <main class="py-6 px-8">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

card/templates/card/add.html
{% extends "base/base.html" %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add link</h1>

    <form action="." method='post' class="mt-6 space-y-4">
        {% csrf_token %}

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <label>Link</label><br>
            <input type="text" name='link' class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

card/templates/card/get.html
{% extends "base/base.html" %}

{% block content %}
    <a href="" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <h1 class="mb-6 text-3xl">{{ card.link }}</h1>

    {% if card.description %}
        <p class='mb-6'>{{ card.description }}</p>
    {% endif %}
{% endblock %}

card/templates/card/get_all.html
{% extends "base/base.html" %}

{% block content %}
    <h1 class="mb-6 text-3xl">Cards</h1>

    <a href="{% url 'card:add' %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Add card</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for card in cards %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'card:card' card.id %}">
                    <h2 class="mb-4 text-xl">{{ card.link }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ card.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}